name: fancy_bottom_bar
description: A different take on your standard bottom app bar. Loosely inspired by \https://dribbble.com/shots/6957731-Reader-app-tab-bar
version: 0.0.1
author: Rob de Knegt <support@cuberob.com>
homepage: https://www.cuberob.com/indie/

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
